global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: node_exporters
    static_configs:
      - targets:
          - 'node_exporter:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
