filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml # enable all modules (nginx, kafka, redis, etc)
    reload.enabled: false

filebeat.autodiscover: # auto-discover tagged docker container
  providers:
    - type: docker
      hints.enabled: true

setup:
  kibana.host: 'http://kibana:5601'
  dashboards.enable: true

# processors:
# - add_cloud_metadata: ~ # for AWS, GCO, Azure etc.
# - add_docker_metadata: ~ # add docker metadata (container id, name, image and labels)

output.elasticsearch:
  hosts: 'http://elasticsearch:9200'
